// <auto-generated />
using System;
using Goldenwood;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Goldenwood.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231023111010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Goldenwood.Model.Building.EconomicBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldIncome")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuilt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TickReduction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoodCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoodIncome")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EconomicBuilding");
                });

            modelBuilder.Entity("Goldenwood.Model.Building.MilitaryBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatableUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldCost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuilt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WoodCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatableUnitId");

                    b.ToTable("MilitaryBuilding");
                });

            modelBuilder.Entity("Goldenwood.Model.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Alive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.ToTable("Enemy");
                });

            modelBuilder.Entity("Goldenwood.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoodAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.Army", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Army");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoodCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.UnitGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArmyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitGroup");
                });

            modelBuilder.Entity("Goldenwood.Model.Building.MilitaryBuilding", b =>
                {
                    b.HasOne("Goldenwood.Model.Units.Unit", "CreatableUnit")
                        .WithMany()
                        .HasForeignKey("CreatableUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatableUnit");
                });

            modelBuilder.Entity("Goldenwood.Model.Enemy", b =>
                {
                    b.HasOne("Goldenwood.Model.Units.Army", "Army")
                        .WithMany()
                        .HasForeignKey("ArmyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Army");
                });

            modelBuilder.Entity("Goldenwood.Model.Player", b =>
                {
                    b.HasOne("Goldenwood.Model.Units.Army", "Army")
                        .WithMany()
                        .HasForeignKey("ArmyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Army");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.UnitGroup", b =>
                {
                    b.HasOne("Goldenwood.Model.Units.Army", null)
                        .WithMany("UnitGroups")
                        .HasForeignKey("ArmyId");

                    b.HasOne("Goldenwood.Model.Units.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.Army", b =>
                {
                    b.Navigation("UnitGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
