// <auto-generated />
using System;
using Goldenwood;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Goldenwood.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Goldenwood.Model.Building.EconomicBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldIncome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickReduction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoodCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoodIncome")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("EconomicBuildings");
                });

            modelBuilder.Entity("Goldenwood.Model.Building.MilitaryBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoodCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("MilitaryBuildings");
                });

            modelBuilder.Entity("Goldenwood.Model.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Alive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("Goldenwood.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoodAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.Army", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Army");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldCost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MilitaryBuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoodCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MilitaryBuildingId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.UnitGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArmyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitGroup");
                });

            modelBuilder.Entity("Goldenwood.Model.Building.EconomicBuilding", b =>
                {
                    b.HasOne("Goldenwood.Model.Player", null)
                        .WithMany("EconomicBuildings")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("Goldenwood.Model.Building.MilitaryBuilding", b =>
                {
                    b.HasOne("Goldenwood.Model.Player", null)
                        .WithMany("MilitaryBuildings")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("Goldenwood.Model.Enemy", b =>
                {
                    b.HasOne("Goldenwood.Model.Units.Army", "Army")
                        .WithMany()
                        .HasForeignKey("ArmyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Army");
                });

            modelBuilder.Entity("Goldenwood.Model.Player", b =>
                {
                    b.HasOne("Goldenwood.Model.Units.Army", "Army")
                        .WithMany()
                        .HasForeignKey("ArmyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Army");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.Unit", b =>
                {
                    b.HasOne("Goldenwood.Model.Building.MilitaryBuilding", null)
                        .WithMany("CreatableUnits")
                        .HasForeignKey("MilitaryBuildingId");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.UnitGroup", b =>
                {
                    b.HasOne("Goldenwood.Model.Units.Army", null)
                        .WithMany("UnitGroups")
                        .HasForeignKey("ArmyId");

                    b.HasOne("Goldenwood.Model.Units.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Goldenwood.Model.Building.MilitaryBuilding", b =>
                {
                    b.Navigation("CreatableUnits");
                });

            modelBuilder.Entity("Goldenwood.Model.Player", b =>
                {
                    b.Navigation("EconomicBuildings");

                    b.Navigation("MilitaryBuildings");
                });

            modelBuilder.Entity("Goldenwood.Model.Units.Army", b =>
                {
                    b.Navigation("UnitGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
